name: 'CI'

on:
  push:
    branches:
    - main
    - features/**
    tags:
    - '*.*.*'
  pull_request:

env:
  DOTNET_NOLOGO: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0
    
    - name: Setup SKDs
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          8.0.x

    - run: dotnet --info
    
    - run: ls
    
    - run: ./create-nuget-config.sh ${{ secrets.NUGETKEY }}

    - run: ./build.sh
    
    - run: ls src/EntityFramework.Storage/artifacts

    - run: |
        dotnet nuget push ./src/EntityFramework.Storage/artifacts/*.nupkg -s https://nuget.pkg.github.com/rk-software-systems/index.json -k ${{ secrets.NUGETKEY }}
